apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-gradle-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-gradle
  template:
    metadata:
      labels:
        app: devops-gradle
    spec:
      containers:
        - name: devops-gradle
          image: merveagacayak/app:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: Password4.
            - name: SERVER_PORT
              value: "8081"
