apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swe304
  template:
    metadata:
      labels:
        app: swe304
    spec:
      containers:
        - name: swe304
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: "swe304"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "Password4."
          ports:
            - containerPort: 5432
