apiVersion: v1
kind: Service
metadata:
  name: devops-gradle-service
spec:
  type: LoadBalancer
  selector:
    app: devops-gradle
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
